name: iglesiasrd
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: Cesar Acosta <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'
  firebase: '^4.3.0'
  google_maps: ">=3.0.0 <4.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  firebase: '^4.3.0'
  google_maps: ">=3.0.0 <4.0.0"

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
